# vod_stepper/refresh_cookies_loop.py

import browser_cookie3
import http.cookiejar as cookielib
import os
import time

def export_youtube_cookies():
    output_path = os.path.join(os.path.dirname(__file__), "cookies.txt")

    try:
        cj = browser_cookie3.firefox(domain_name="youtube.com")

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is automatically generated.\n\n")

            for cookie in cj:
                f.write(
                    "\t".join([
                        cookie.domain,
                        "TRUE" if cookie.domain_initial_dot else "FALSE",
                        cookie.path,
                        "TRUE" if cookie.secure else "FALSE",
                        str(cookie.expires or 0),
                        cookie.name,
                        cookie.value
                    ]) + "\n"
                )

        print(f"✅ cookies.txt refreshed")

    except Exception as e:
        print(f"❌ Failed to refresh cookies: {e}")

if __name__ == "__main__":
    INTERVAL_MINUTES = 30

    print(f"🔁 Starting cookie refresher loop — every {INTERVAL_MINUTES} minutes")
    while True:
        export_youtube_cookies()
        time.sleep(INTERVAL_MINUTES * 60)
